### ISSUE TITLE
Bandcamp collections playlist has white background.

### ISSUE THREAD

**Issue by cladmi** [jasuthemes/userstyles#3]
When playing music on the personal collection page, the play queue popup has a white background.

The song names are written in white on white background.

I tried to hack something from Firefox inspect and your existing color found in other CSS entries.
But I am no CSS dev or style expert.

This works for playing, selected music, hovering and also when it's hiding.

```
    .carousel-player .queue {
        background: #303030;
    }
    .carousel-player .queue li.active {
        background: #262626;
        border-left: 2px solid #eaeaea;
        border-bottom: 1px solid #eaeaea;
        border-top: 1px solid #eaeaea;
    }
    .carousel-player .queue li.focus {
        background: #282828;
        border: 1px solid #282828;
    }
```

Would be good to have these configured too by default.

Not doing a PR as unsure about the actual values to put there, I would just like to have a value.

Thanks in advance.

**Comment by jasuthemes** [comment]
Hi cladmi,

I just released an update which should hopefully have addressed the issues. Thanks for the report!

**Comment by jasuthemes** [comment]
Hi cladmi,

I just released an update which should hopefully have addressed the issues. Thanks for the report!

**Comment by cladmi** [comment]
Perfect thank you!
